name: workflow_1 # название рабочего процесса
on: workflow_dispatch # событие при котором запускается рабочий процесс
jobs: # список заданий
  print: # название задания
    runs-on: ubuntu-latest # среда в которой запускается задание
    steps: # шаги из которых состоит задание, шаги выполняются последовательно
      - name: Print text # имя шага
        run: echo Hello! # действие которое выполняется на этом шаге
      #название шага можно не указывать, тогда вместо него подставиться первая строка кода
      - run: | # с помощью вертикальной черты можно последовательно выполнить несколько строк кода
          echo First_string
          echo Second_string
      - name: checkout repo
        uses: action/checkout@v3
      - run: make say-hello
        
